language: python
cache: pip

python:
  - "2.7"
  - "3.6"

sudo: required

services:
  - docker

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0


matrix:
  include:
    - { python: "3.6", env: TOXENV=lint }
  exclude:
    - { python: "2.7", env: DJANGO=2.0 }


install:
  - pip install tox tox-travis
script: "tox"
after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO