# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V1Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='V2Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='V3Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baz', models.CharField(max_length=16)),
            ],
        ),
    ]
